require:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.3
  NewCops: enable

Minitest/MultipleAssertions:
  Max: 10 # default 3

Rails/CreateTableWithTimestamps:
  Exclude:
    - db/migrate/20240517075643_initial_schema.rb

Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_password_reset_token
    - find_by_password_reset_token!

Style/FrozenStringLiteralComment:
  Enabled: true

