
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

require:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.4
  NewCops: enable


Capybara/ClickLinkOrButtonStyle:
  EnforcedStyle: strict

Minitest/MultipleAssertions:
  Max: 10 # default 3

Rails/CreateTableWithTimestamps:
  Exclude:
    - db/migrate/20240517075643_initial_schema.rb

Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_password_reset_token
    - find_by_password_reset_token!

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Layout/IndentationWidth:
  Enabled: true

# Layout/LineLength:
#   Max: 120
